# Possible colors: AQUA, BLACK, BLUE, DARK_AQUA, DARK_BLUE, DARK_GRAY, DARK_GREEN
# DARK_PURPLE, DARK_RED, GOLD, GRAY, GREEN, LIGHT_PURPLE, RED, WHITE, YELLOW.
colors:
  say: LIGHT_PURPLE
  msay: LIGHT_PURPLE
  osay: LIGHT_PURPLE