name: ${name}
main: ${groupId}.${artifactId}.${name}
version: ${version}
commands:
   say:
      description: Broadcasts the given message as the console.
      usage: /say <message ...>
      permission: bukkit.command.say
      permission-message: You don't have permission to use this command.
      
   msay:
      description: Broadcasts the given message as yourself.
      usage: /msay <message ...>
      permission: bukkit.command.say
      permission-message: You don't have permission to use this command.
      
   osay:
      description: Broadcasts the given message as someone else.
      usage: /osay <name> <message ...>
      permission: bukkit.command.say
      permission-message: You don't have permission to use this command.